obj-$(CONFIG_SCHED_EMS) += ems.o
ems-y := core.o energy.o multi_load.o ontime.o sparing.o cpu_select.o freq_boost.o hook.o sysbusy.o idle.o
ems-$(CONFIG_CPU_FREQ_GOV_ENERGYSTEP) += energy_step.o
ems-$(CONFIG_SCHED_USE_FLUID_RT) += frt.o
ems-$(CONFIG_SCHED_EMS_TUNE) += tune.o
