# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -std=gnu11
ccflags-$(CONFIG_RTL8XXXU_UNTESTED) += -DCONFIG_RTL8XXXU_UNTESTED

obj-$(CONFIG_RTL8XXXU) += rtl8xxxu_git.o

rtl8xxxu_git-y := core.o 8192e.o 8723b.o \
		 8723a.o 8192c.o 8188f.o \
		 8188e.o 8710b.o 8192f.o
